// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhljcpoaL6RSyZMI8uoz2LB5325BF0e8',
    appId: '1:638639771003:web:f4a450278ac0fed5d881de',
    messagingSenderId: '638639771003',
    projectId: 'authtutorial-fd130',
    authDomain: 'authtutorial-fd130.firebaseapp.com',
    storageBucket: 'authtutorial-fd130.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Ry4_aGcGoQPKliHvGYn8NcX3TJh91Gk',
    appId: '1:638639771003:android:31b88fafb48292cdd881de',
    messagingSenderId: '638639771003',
    projectId: 'authtutorial-fd130',
    storageBucket: 'authtutorial-fd130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiTs7lKG3t6RLw3CDAt2AjAp1XJLgCDQw',
    appId: '1:638639771003:ios:2479bfcfa2e5befed881de',
    messagingSenderId: '638639771003',
    projectId: 'authtutorial-fd130',
    storageBucket: 'authtutorial-fd130.appspot.com',
    iosBundleId: 'com.example.simpleLoginSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiTs7lKG3t6RLw3CDAt2AjAp1XJLgCDQw',
    appId: '1:638639771003:ios:242d3bea71ffd0acd881de',
    messagingSenderId: '638639771003',
    projectId: 'authtutorial-fd130',
    storageBucket: 'authtutorial-fd130.appspot.com',
    iosBundleId: 'com.example.loginSystemTutorial1',
  );
}
